context:
  version: 1.13.0
  name: scipy

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/fb/a3/328965862f41ba67d27ddd26205962007ec87d99eec6d364a29bf00ac093/scipy-1.13.0.tar.gz
  sha256: 58569af537ea29d3f78e5abd18398459f195546bb3be23d16677fb26616cc11e

build:
  number: 1

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx')}}
  - cython
  - pkg-config
  - libtool
  - python
  - python-build
  - meson-python
  - pythran
  - ninja
  - click
  - pydevtool

  host:
  - python
  - pybind11
  - libblas>=3.12
  - libcblas>=3.12
  - liblapack>=3.12
  - libflang
  - numpy
  - pythran

  run:
  - python

extra:
  recipe-maintainers:
  - DerThorsten
  - KGB99